/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppBadge: typeof import('./src/components/ui/AppBadge.vue')['default']
    AppButton: typeof import('./src/components/ui/AppButton.vue')['default']
    AppCard: typeof import('./src/components/ui/AppCard.vue')['default']
    AppConfirm: typeof import('./src/components/ui/AppConfirm.vue')['default']
    AppEmpty: typeof import('./src/components/ui/AppEmpty.vue')['default']
    AppInput: typeof import('./src/components/ui/AppInput.vue')['default']
    AppLayout: typeof import('./src/components/AppLayout.vue')['default']
    AppModal: typeof import('./src/components/ui/AppModal.vue')['default']
    AppPagination: typeof import('./src/components/ui/AppPagination.vue')['default']
    AppSelect: typeof import('./src/components/ui/AppSelect.vue')['default']
    AppToast: typeof import('./src/components/ui/AppToast.vue')['default']
    AppToggle: typeof import('./src/components/ui/AppToggle.vue')['default']
    BottomNav: typeof import('./src/components/BottomNav.vue')['default']
    LatexRender: typeof import('./src/components/LatexRender.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ThemeToggle: typeof import('./src/components/ThemeToggle.vue')['default']
    WelcomeScreen: typeof import('./src/components/WelcomeScreen.vue')['default']
  }
}
