// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 一种解法（导出引擎复用；TS 绑定随 exam.ts 一并导出）
 */
export type AnalysisBlock = { id: string, title: string, content: string, };

/**
 * 问树节点（递归）
 */
export type QuestionPart = { id: string, label: string, stem: string, children: Array<QuestionPart>, answer: string | null, analyses: Array<AnalysisBlock>, no_analysis_needed: boolean, 
/**
 * 为 true 时编号重排不覆盖 label
 */
label_dirty: boolean, };
