// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 密封线（`None` = 不装订）
 */
export type Binding = { position: BindingPosition, areas: BindingAreas, };

/**
 * 密封线旁的填涂区开关
 */
export type BindingAreas = { school: boolean, 
/**
 * 班级（`class` 是 Rust 关键字，序列化出去仍叫 class）
 */
class: boolean, name: boolean, exam_no: boolean, };

/**
 * 装订位
 */
export type BindingPosition = "left" | "center_fold";

/**
 * 留白样式与默认高度。**是否留白与最终高度由 `options.answer_space` 裁决**（B5）
 */
export type BlankSpec = { style: BlankStyle, 
/**
 * options 没给高度时的兜底高度（cm）
 */
height_cm: number, };

/**
 * 答题留白样式
 */
export type BlankStyle = "lines" | "dots" | "blank";

/**
 * 印前色彩模式
 */
export type ColorMode = "rich" | "print_black_only";

/**
 * 字体族名（typst `set text(font: ...)` 直接吃）
 */
export type FontSpec = { 
/**
 * 正文：思源宋体
 */
body: string, 
/**
 * 标题：思源黑体
 */
heading: string, 
/**
 * 数学：typst 内嵌的 New Computer Modern
 */
math: string, };

/**
 * 页眉页脚开关。动态页眉取当前大题名（T4.10）与按逻辑页判定的奇偶外侧对齐（T4.7）尚未实现，
 * 字段先按 §6.1 定齐，免得 M4 再改前端 TS 类型
 */
export type HeaderFooter = { 
/**
 * 页眉：当前大题名
 */
header_title: boolean, 
/**
 * 页脚：第 X 页 共 Y 页
 */
page_number: boolean, 
/**
 * 奇偶页码外侧对齐（双面印）
 */
odd_even_outer: boolean, };

/**
 * 版面参数（§6.1 全字段）
 */
export type LayoutSpec = { paper: Paper, 
/**
 * 1 | 2 | 3
 */
columns: number, margins: Margins, binding: Binding | null, header_footer: HeaderFooter, profile: OutputProfile, fonts: FontSpec, answer_blank: BlankSpec, color: ColorMode, };

/**
 * 四边边距 + 栏间距（mm）
 */
export type Margins = { top_mm: number, right_mm: number, bottom_mm: number, left_mm: number, 
/**
 * 栏间距；单栏时由 [`LayoutSpec::column_gutter_mm`] 归零
 */
gutter_mm: number, };

/**
 * 出片对象。与导出域的 `ExportMode` 同形但独立 —— typeset 不依赖 export
 */
export type OutputProfile = "student" | "teacher" | "exam";

/**
 * 纸张：M3 基础版只用 `A4`；两档 A3 的字段先定齐，对折与三栏的版式在 T4.7/T4.8 落地
 */
export type Paper = "a4" | "a3_fold" | "a3_tri";

/**
 * `GET /typeset/profiles` 的列表项
 */
export type ProfilePreset = { id: string, 
/**
 * 中文标签，前端下拉直接用
 */
label: string, spec: LayoutSpec, };

/**
 * B5 合并后的留白：排版器只认这一份
 */
export type ResolvedBlank = { style: BlankStyle, height_mm: number, };
