// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Issue } from "./exam";

/**
 * 密封线（`None` = 不装订）
 */
export type Binding = { position: BindingPosition, areas: BindingAreas, };

/**
 * 密封线旁的填涂区开关
 */
export type BindingAreas = { school: boolean, 
/**
 * 班级（`class` 是 Rust 关键字，序列化出去仍叫 class）
 */
class: boolean, name: boolean, exam_no: boolean, };

/**
 * 装订位
 */
export type BindingPosition = "left" | "center_fold";

/**
 * 留白样式与默认高度。是否留白与最终样式按「题级 → 卷级 options → 本字段」取用（B5）
 */
export type BlankSpec = { style: BlankStyle, 
/**
 * options 没给高度时的兜底高度（cm）
 */
height_cm: number, };

/**
 * 答题留白样式
 */
export type BlankStyle = "lines" | "dots" | "blank";

/**
 * 印前色彩模式
 */
export type ColorMode = "rich" | "print_black_only";

/**
 * 字体族名（typst `set text(font: ...)` 直接吃）
 */
export type FontSpec = { 
/**
 * 正文：思源宋体
 */
body: string, 
/**
 * 标题：思源黑体
 */
heading: string, 
/**
 * 数学字体：两个出口当前都没有落点 —— typst 0.15 的方程元素把自己的字体硬设成
 * New Computer Modern Math（见 `typeset::typst_gen` 的实测说明），docx 的 OMML 由
 * Word 自行选字体。字段按 §6.1 定齐，等真能落地时再生效
 */
math: string, };

/**
 * 页眉页脚开关。页码按**逻辑页**计（T4.7 / R4：A3 对折的一张纸报两页号），奇偶外侧对齐同期
 * 落地；`header_title` 开的是逐栏取当前大题名的动态页眉（T4.10）
 */
export type HeaderFooter = { 
/**
 * 页眉：当前大题名
 */
header_title: boolean, 
/**
 * 页脚：第 X 页 共 Y 页
 */
page_number: boolean, 
/**
 * 奇偶页码外侧对齐（双面印）
 */
odd_even_outer: boolean, };

/**
 * 版面参数（§6.1 全字段）
 */
export type LayoutSpec = { paper: Paper, 
/**
 * 1 | 2 | 3
 */
columns: number, margins: Margins, binding: Binding | null, header_footer: HeaderFooter, profile: OutputProfile, fonts: FontSpec, answer_blank: BlankSpec, color: ColorMode, };

/**
 * 四边边距 + 栏间距（mm）
 */
export type Margins = { top_mm: number, right_mm: number, bottom_mm: number, left_mm: number, 
/**
 * 栏间距；单栏时由 [`LayoutSpec::column_gutter_mm`] 归零
 */
gutter_mm: number, };

/**
 * 出片对象。与导出域的 `ExportMode` 同形但独立 —— typeset 不依赖 export
 */
export type OutputProfile = "student" | "teacher" | "exam";

/**
 * 纸张：A3 两档都按长边横置出纸；一张纸算几个「逻辑页」由 `Paper::logical_slots_per_sheet` 定
 */
export type Paper = "a4" | "a3_fold" | "a3_tri";

/**
 * `POST /typeset/preview` 的响应（§6.5）
 *
 * 裸载荷、无信封，与 `/export/*` 的文件响应一致。`pages` 的下标是**物理页**：A3 对折卷一张纸
 * 两个逻辑页（R4），预览里就是一页纸上左右两栏，教师看到的就是要印的东西。
 */
export type PreviewResponse = { 
/**
 * 逐页 SVG 源码，自包含（字形已描边，浏览器无需装字体），代价是文字不可选中
 */
pages: Array<string>, page_count: number, 
/**
 * 生成期问题（装配、素材、公式降级）+ 印前预检发现（T5.1），全部结构化
 */
issues: Array<Issue>, 
/**
 * typst 自己的告警原文：给人看即可，不值得编成 `Issue`
 */
warnings: Array<string>, };

/**
 * `GET /typeset/profiles` 的列表项
 */
export type ProfilePreset = { id: string, 
/**
 * 中文标签，前端下拉直接用
 */
label: string, spec: LayoutSpec, };

/**
 * B5 合并后的留白：排版器只认这一份
 */
export type ResolvedBlank = { style: BlankStyle, height_mm: number, };
